### ISSUE TITLE
Feat: Category Indicator Issue

### ISSUE THREAD

**Issue by dolly4657** [dolly4657/ToDO_App#2]
Report a missing active underline to indicate the selected category in the to-do app.

### Issue Description

**Summary:**
The to-do app currently lacks a clear indicator to show the selected category, such as "All," "Completed," or "Pending." This omission can potentially lead to confusion for users, as they may not know which category they are currently viewing. This issue aims to address this by adding a visual indicator.

**Expected Behavior:**
When a user clicks on one of the categories, there should be a visible and active underline or some other clear visual to indicate which category is currently selected. This will improve the user experience and provide clarity when navigating the app.

**Current Behavior:**
At present, there is no active underline or any other visual indicator to distinguish the selected category from the others, making it difficult for users to know which category they are viewing.

**Comment by wrth1337** [comment]
I'd like to work on this issue :)
